CREATE TABLE MSU_SCHEDULE
(
  TASK_ID                  VARCHAR2(50) NOT NULL,
  SCHEDULE_ID         VARCHAR2(50) NOT NULL,
  SCHEDULE_POINT      NUMBER(20) NOT NULL,
  CREATE_AT           NUMBER(20) NOT NULL,
  REGION      VARCHAR2(50) NOT NULL,
  OPERATION   VARCHAR2(50) NOT NULL,
  FETCH_AT            NUMBER(20),
  FETCH_BY            VARCHAR2(50),
  EXECUTE_AT          NUMBER(20),
  EXECUTE_COST        NUMBER(20),
  EXECUTE_STATUS      NUMBER(1),
  EXECUTE_DESCRIPTION VARCHAR2(500)
)
;
COMMENT ON TABLE MSU_SCHEDULE
  IS '任务调度执行表';
COMMENT ON COLUMN MSU_SCHEDULE.TASK_ID
  IS '任务标识ID';
COMMENT ON COLUMN MSU_SCHEDULE.SCHEDULE_ID
  IS '任务调度ID';
COMMENT ON COLUMN MSU_SCHEDULE.SCHEDULE_POINT
  IS '调度时间';
COMMENT ON COLUMN MSU_SCHEDULE.CREATE_AT
  IS '入库时间';
COMMENT ON COLUMN MSU_SCHEDULE.REGION
  IS '省市县编码';
COMMENT ON COLUMN MSU_SCHEDULE.OPERATION
  IS '任务操作';
COMMENT ON COLUMN MSU_SCHEDULE.FETCH_AT
  IS '获取时间';
COMMENT ON COLUMN MSU_SCHEDULE.FETCH_BY
  IS '获取者';
COMMENT ON COLUMN MSU_SCHEDULE.EXECUTE_AT
  IS '执行时间';
COMMENT ON COLUMN MSU_SCHEDULE.EXECUTE_COST
  IS '执行时长';
COMMENT ON COLUMN MSU_SCHEDULE.EXECUTE_STATUS
  IS '执行情况';
COMMENT ON COLUMN MSU_SCHEDULE.EXECUTE_DESCRIPTION
  IS '执行描述';
ALTER TABLE MSU_SCHEDULE
  ADD CONSTRAINT MSU_SCHEDULE_KEY_ID PRIMARY KEY (SCHEDULE_ID);

PROMPT CREATING MSU_TASK...
CREATE TABLE MSU_TASK
(
  ID          VARCHAR2(50) NOT NULL,
  REGION      VARCHAR2(50) NOT NULL,
  CREATE_AT   NUMBER(20) NOT NULL,
  SCHEDULE    VARCHAR2(50) NOT NULL,
  OPERATION   VARCHAR2(50) NOT NULL,
  TARGET_IP   VARCHAR2(50) NOT NULL,
  TARGET_PORT NUMBER(5) NOT NULL,
  CONTENT     VARCHAR2(1000) NOT NULL,
  META_DATA VARCHAR2(500) NOT NULL,
  RES_ID      NUMBER(20) NOT NULL,
  IS_REALTIME NUMBER(1) DEFAULT 1
)
;
COMMENT ON TABLE MSU_TASK
  IS '任务信息表';
COMMENT ON COLUMN MSU_TASK.ID
  IS '任务标识ID';
COMMENT ON COLUMN MSU_TASK.REGION
  IS '省市县编码';
COMMENT ON COLUMN MSU_TASK.CREATE_AT
  IS '创建时间';
COMMENT ON COLUMN MSU_TASK.SCHEDULE
  IS '调度规则';
COMMENT ON COLUMN MSU_TASK.OPERATION
  IS '任务操作';
COMMENT ON COLUMN MSU_TASK.TARGET_IP
  IS '采集IP';
COMMENT ON COLUMN MSU_TASK.TARGET_PORT
  IS '采集端口';
COMMENT ON COLUMN MSU_TASK.META_DATA
  IS '任务数据';
COMMENT ON COLUMN MSU_TASK.CONTENT
  IS '任务内容';
COMMENT ON COLUMN MSU_TASK.RES_ID
  IS '资源ID';
COMMENT ON COLUMN MSU_TASK.IS_REALTIME
  IS 'REALTIME';
ALTER TABLE MSU_TASK
  ADD CONSTRAINT MSU_TASK_KEY_ID PRIMARY KEY (ID);
